[package]
name = "schnose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
gokz_rs = "0.1.0"
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3.24"

[dependencies.serenity]
version = "0.11"
default-features = false
features = [
	"client",
	"gateway",
	"framework",
	"standard_framework",
	"rustls_backend",
	"model"
]
