[package]
name = "schnose"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
gokz_rs = "0.4"
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3.24"
chrono = "0.4"
mongodb = "2.1"
bson = { version = "2", features = ["chrono-0_4"] }
serde = "1"
regex = "1.6.0"
rand = "0.8.5"
num-format = "0.4.3"
tracing = "0.1.37"

[dependencies.serenity]
version = "0.11"
default-features = false
features = [
	"client",
	"gateway",
	"framework",
	"standard_framework",
	"rustls_backend",
	"model"
]
